{% set name = "rs_bag2image" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: ..

build:
  number: 0
  script_env:
    - REALSENSE2_DIR

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
  host:
    - boost-cpp
    - libopencv
  run:
    - boost-cpp
    - libopencv

test:
  commands:
    - rs_bag2image --help

about:
  home: https://github.com/UnaNancyOwen/rs_bag2image
  license: MIT
  license_file: LICENSE
  summary: Tool to convert bag files to image files for RealSense

extra:
  recipe-maintainers:
    - jakirkham
